toolchain("mips-linux-gnu")
    set_kind("standalone")
    set_sdkdir("/opt/mips-gcc472-glibc216-32bit")
    set_bindir("/opt/mips-gcc472-glibc216-32bit/bin")
    add_cxflags("-muclibc", "-march=mips32r2")
    add_ldflags("-muclibc")
toolchain_end()
